### ISSUE TITLE
Help on running test data

### ISSUE THREAD

**Issue by sanbio** [dePamphilis/PlantTribes#20]
Respected Sir / Madam,
I am very much interested in using PlantTribes for my research work but finding some problem in installing and running the pipeline. I am trying to run the test data but it gives some errors as below:
############ Target Family - Orthogroup 213 ############

HMM profile for orthogroup 213 doesn't exist for orthomcl method of scaffold 37Gv1.0!

############ Target Family - Orthogroup 4632 ############

HMM profile for orthogroup 4632 doesn't exist for orthomcl method of scaffold 37Gv1.0!

kindly help me in troubleshooting the same for which I will be thankful to you.

Sincerely yours
Santosh Vishwakarma

**Comment by ewafula** [comment]
Santosh,

The test data for the targeted gene family can only be used for 22Gv1.1
gene family scaffold with the orthomcl clustering method as illustrated in
the tutorial. You must know some functional info of an orthogroup you want
to target to improve contiguity of your de novo assembly transcripts for
that particular gene family.  A good use case would be if you have
tissue-specific assemblies and non of them including the combined assembly
of all tissues gives a complete reconstructed transcripts, but you want to
check if all the fragmented pieces from all the assemblies can yield a near
full-length transcript if guided by reference gene model(s). Target
orthogroup IDs for the test data  are from a select few single-copy genes
orthogroups of the 22Gv1.1 orthomcl method. The annotation summary table
provides detailed functional annotation of every scaffold orthogroup. Each
gene family scaffold method has it own orthogroups labeled sequentially
from the largest to smallest size. Unlike the 22Gv1.1 scaffold whose
proteomes were clustered with three method (gram, orthomcl, and
orthofinder), the 37Gv1.0 scaffold was only clustered with orthofinder
method. You must have seen only data for one method in the download of the
37Gv1.1 scaffold and corresponding config files.

Please follow the tutorial if you want to test your set up of PlantTribes.
If the commandline version seems daunting, try the GUI version available on
the public galaxy server,  https://usegalaxy.org/. There is a detailed step
by step tutorial available at
https://galaxyproject.org/tutorials/pt_gfam/. To avoid queuing, you could
also set up your own instance of galaxy (
https://galaxyproject.org/admin/get-galaxy/) and install PlantTribes tools
and a plethora of other community contributed tools from the Galaxy
ToolShed (https://galaxyproject.org/toolshed/).

Hopefully, that helps.

Eric
