### ISSUE TITLE
kaksAnalysis pipeline error!

### ISSUE THREAD

**Issue by sunnycqcn** [dePamphilis/PlantTribes#21]
Hello Eric,
When I used kaksAnalysis pipeline to analyze Striga genome. I met a error as following. It looks like MAFFT version. I installed the MAFFT v7.245 from conda. I am not sure I should only install version 7.215. Or I met other error.
Thanks,
Fuyou

 nseq =  2
distance =  local
iterate =  16
cycle =  1
nthread = 40
lastonce = 0
done.
scoremtx = 1
    0 / 2 (by thread   1)

##### writing hat3
pairlocalalign (aa) Version 7.245 alg=L, model=BLOSUM62, 2.00, -0.10, +0.10, noshift, amax=0.0
40 thread(s)
minimumweight = 0.000500
nthread = 40
blosum 62 / kimura 200
sueff_global = 0.100000
Loading 'hat3' ...
done.
done.
scoremtx = 1
Gap Penalty = -1.53, +0.00, +0.00
Loading 'hat2' ... done.
Constructing a UPGMA tree ...
    0 / 2
done.

Progressive alignment ...
STEP     1 /1 (thread    1) c
done.
tbfast (aa) Version 7.245 alg=A, model=BLOSUM62, 1.53, -0.00, -0.00, noshift, amax=0.0
40 thread(s)
minimumweight = 0.000500
autosubalignment = 0.000000
nthread = 10
randomseed = 0
blosum 62 / kimura 200
poffset = 0
niter = 16
sueff_global = 0.100000
Loading 'hat3' ... done.
done.
scoremtx = 1

    0 / 2
Segment   1/  1    1- 448
001-0000-1 (thread    2) identical
Converged.

Reached 1
done
dvtditr (aa) Version 7.245 alg=A, model=BLOSUM62, 1.53, -0.00, -0.00, noshift, amax=0.0
10 thread(s)

Strategy:
 L-INS-i (Probably most accurate, very slow)
 Iterative refinement method (<16) with LOCAL pairwise alignment information

If unsure which option to use, try 'mafft --auto input > output'.
For more information, see 'mafft --help', 'mafft --man' and the mafft page.

The default gap scoring scheme has been changed in version 7.110 (2013 Oct).
It tends to insert more gaps into gap-rich regions than previous versions.
To disable this change, add the --leavegappyregion option.

Use of uninitialized value $ortho_id in concatenation (.) or string at /home/AAFC-AAC/fuf/miniconda3/envs/PlantT/bin/KaKsAnalysis line 650.
Use of uninitialized value $aln_len in concatenation (.) or string at /home/AAFC-AAC/fuf/miniconda3/envs/PlantT/bin/KaKsAnalysis line 432.
Use of uninitialized value in concatenation (.) or string at /home/AAFC-AAC/fuf/miniconda3/envs/PlantT/bin/KaKsAnalysis line 433.
Use of uninitialized value in subtraction (-) at /home/AAFC-AAC/fuf/miniconda3/envs/PlantT/bin/KaKsAnalysis line 436.

Error: seq err1: EOF.

**Comment by ewafula** [comment]
Looking at your pipeline run log, Mafft seems to have been running okay but
terminated for some reason. I am not sure what the reason is, but most
likely has to do with your data. Please make sure that all the external
dependent tools are properly installed in your environment and working
properly. There is a step by step tutorial on the GitHub repository that
shows how to run the pipeline using a small test dataset that comes along
with distribution. Use this small test dataset to test pipeline
installation. The majority of the errors have to with either the input
datasets or external dependencies.
